### ISSUE TITLE
Module "pygments" requires but the package doesn't contain it

### ISSUE THREAD

**Issue by StardustDL** [eXceediDeaL/edl-coderunner#1]
When install with pip, ecr will raise ImportError for "pygments" not found.

BTW, add installing and running test for next version? Because in this version, the tests are not runnable.

**Comment by eXceediDeaL** [comment]
Fixed the bug "no module pygments".

Because it use prompt_toolkit, using pytest will raise some error, so it use shellscript to test installing and using. There will be more tests in the future.
