### ISSUE TITLE
Add global config

### ISSUE THREAD

**Issue by StardustDL** [eXceediDeaL/edl-coderunner#5]
# Problem

When use ecr in a new directory, we must initialize first, but sometimes, we use the same config.

# Solution

Add a global config. It will be used when there is not a local config. To realize this, create a global config directory, and check it when load.

# Alternative

- Maybe add more items in global config?
  - `user.name` or anything else
- Add config backup?

**Comment by eXceediDeaL** [comment]
Finished. Add these features:
- Global config initializing and loading
- `init -d` and `clear -d`
