### ISSUE TITLE
Add reload command and loading status

### ISSUE THREAD

**Issue by StardustDL** [eXceediDeaL/edl-coderunner#6]
# Problem

When config loading failed, it won't give any information to fix it.

# Solution

- Show loading log when failed to load
- Add `reload` command to reload config without restarting.

# Alternative

- Add loading log to debug data and use `debug` command to show it
- Add log data(?)
  - Add `verbose` option for log

**Comment by eXceediDeaL** [comment]
Finished. Add these features:
- `reload` command
- `--verbose` option
- logging support (**not full**)
- `debug --log` to show logs
